### ISSUE TITLE
nsd_pycortex_db error, Missing the the related matrices.xfms for subj01-8"

### ISSUE THREAD

**Issue by Zhangzhixiang-laugh** [ariaaay/clip2brain#11]
1. **How to solove the inconsistency with the different db?**

**The db you provided:**
![image](https://github.com/user-attachments/assets/6e92105c-0ddc-457f-8920-d13859819086)
**The source db:**
![image](https://github.com/user-attachments/assets/9925f55b-cc3f-4589-a5c7-1c399324847d)
Error info:
/home/jack/anaconda3/envs/brainnet/bin/python3.9 /mnt/d/github projects/clip2brain-main/src/visualize_in_pycortex.py 
Namespace(subj=1, mask_sig=True, sig_method='negtail_fdr', alpha=0.05, show_pcs=False, show_clustering=False, show_more=False, show_repr_sim=False, vis_method='quickflat')
Traceback (most recent call last):
  File "/mnt/d/github projects/clip2brain-main/src/visualize_in_pycortex.py", line 510, in <module>
    volumes["clip-ViT-last R^2 NC"] = make_volume(
  File "/mnt/d/github projects/clip2brain-main/src/visualize_in_pycortex.py", line 136, in make_volume
    mask = cortex.utils.get_cortical_mask(
  File "/home/jack/anaconda3/envs/brainnet/lib/python3.9/site-packages/cortex/utils.py", line 184, in get_cortical_mask
    return get_mapper(subject, xfmname, type=type).mask
  File "/home/jack/anaconda3/envs/brainnet/lib/python3.9/site-packages/cortex/utils.py", line 32, in __call__
    return self._load()(*args, **kwargs)
  File "/home/jack/anaconda3/envs/brainnet/lib/python3.9/site-packages/cortex/mapper/__init__.py", line 32, in get_mapper
    xfmfile = db.get_paths(subject)['xfmdir'].format(xfmname=xfmname)
  File "/home/jack/anaconda3/envs/brainnet/lib/python3.9/site-packages/cortex/database.py", line 672, in get_paths
    for surf in os.listdir(surfpath):
**FileNotFoundError: [Errno 2] No such file or directory: '/home/jack/anaconda3/envs/brainnet/share/pycortex/db/subj01/surfaces'**
Process finished with exit code 1

2. running the visualize_in_pycortex.py with the error - **Missing the matrices.xfm?**:

   ` vol_data = cortex.dataset.Volume(
        all_vals,
        "subj%02d" % subj,
        "func1pt0_to_anat0pt8_autoFSbbr",
        mask=mask,
        cmap=cmap,
        vmin=vmin,
        vmax=vmax,
    )`

  Errof info:
  Traceback (most recent call last):
  File "/mnt/d/github projects/clip2brain-main/src/visualize_in_pycortex.py", line 461, in <module>
    volumes["clip-laion2b R^2"] = make_volume(
  File "/mnt/d/github projects/clip2brain-main/src/visualize_in_pycortex.py", line 229, in make_volume
    vol_data = cortex.dataset.Volume(
  File "/home/jack/anaconda3/envs/brainnet/lib/python3.9/site-packages/cortex/dataset/views.py", line 283, in __init__
    super(Volume, self).__init__(data, subject, xfmname, mask=mask, 
  File "/home/jack/anaconda3/envs/brainnet/lib/python3.9/site-packages/cortex/dataset/braindata.py", line 146, in __init__
    self._check_size(mask)
  File "/home/jack/anaconda3/envs/brainnet/lib/python3.9/site-packages/cortex/dataset/braindata.py", line 240, in _check_size
    xfm = db.get_xfm(self.subject, self.xfmname)
  File "/home/jack/anaconda3/envs/brainnet/lib/python3.9/site-packages/cortex/database.py", line 463, in get_xfm
    with open(fname) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/home/jack/anaconda3/envs/brainnet/share/pycortex/db/subj01/transforms/func1pt0_to_anat0pt8_autoFSbbr/**matrices.xfm**'

**Comment by Zhangzhixiang-laugh** [comment]
Everything works fine, note that download the individual files of each subject rather than merge the whole files. I lost the .xfm files while uncompressing the whole .zip with goggle cloud.
